config/routes.rb
Rails.application.routes.draw do
  root to: 'channels#index'
  devise_for :users
  resources :channels do
    resources :tweets, only: [:index, :show, :create]
    resources :chats do
      resource :messages, only: [:create]
    end
    resources :events do
      resources :channel_event_users, only: [:create, :destroy]
    end
    resources :albums
    resources :topics, only: [:new ,:create,  :edit ,:update ,:destroy] 
  end
  resource :sessions, only: [:index, :new, :create, :destroy]
  resources :users, only: [:show, :edit ,:update, :destroy]
end

app/models/channel.rb
class Channel < ApplicationRecord
  # Association
  has_one_attached :channel_main_image
  has_one_attached :channel_background_image

  has_secure_password

  has_many :channel_users, dependent: :destroy
  has_many :users, through: :channel_users
  has_many :administrators, -> { where(channel_users: { administrator: true }) }, through: :channel_users, source: :user
  has_many :albums, dependent: :destroy
  has_many :tweets, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_many :topics, dependent: :destroy
  has_many :events, dependent: :destroy

  # Validation
  validates :name, presence: true
  validates :identification, presence: true, uniqueness: true
  validates :password, presence: true, confirmation: true, length: { minimum: 6, maximum: 128 }, if: :password_required?
  # validates :introduction

  def password_required?
    new_record? || password.present? || password_confirmation.present?
  end
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_channel, only: [:show, :edit, :update, :destroy]
  before_action :ensure_correct_channel_user, only: [:show, :edit, :update, :destroy]

  def index
    @channels = current_user.channels.includes(:channel_users)
    @identification = params[:identification]
    @password = params[:password]
  end

  def new
    @channel = Channel.new
    @users = User.all
  end

  def create
    @channel = Channel.new(channel_params)
    if @channel.save
      (params[:administrators] || []).each do |administrator_id|
        @channel.channel_users.create(user_id: administrator_id, administrator: true)
      end
      (params[:users] || []).each do |user_id|
        unless @channel.channel_users.where(user_id:, administrator: true).exists?
          @channel.channel_users.create(user_id:, administrator: false)
        end
      end
      redirect_to channels_path
    else
      @users = User.all
      render :new, status: :unprocessable_entity
    end
  end

  def show
    session[:channel_id] = @channel.id
    @administrators = @channel.administrators
    @channel_users = @channel.channel_users
    @events = @channel.events.where('date_end >= ?', Date.today).order(created_at: :desc)
    @topics = @channel.topics.order(created_at: :desc)
  end

  def edit
    @users = User.all
    return if @channel.administrators.include?(current_user)

    redirect_to channel_path(@channel), alert: 'あなたはこのチャンネルの管理者ではありません。'
  end

  def update
    if @channel.update(channel_params)
      (params[:administrators] || []).each do |administrator_id|
        @channel.channel_users.find_or_create_by(user_id: administrator_id, administrator: true)
      end
      (params[:users] || []).each do |user_id|
        unless @channel.channel_users.where(user_id:, administrator: true).exists?
          @channel.channel_users.find_or_create_by(user_id:, administrator: false)
        end
      end
      redirect_to channel_path(params[:id])
    else
      @users = User.all
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @channel.destroy
    redirect_to root_path
  end

  private

  def set_channel
    @channel = Channel.find(params[:id])
  end

  def ensure_correct_channel_user
    return if @channel.channel_users.exists?(user_id: current_user.id)

    redirect_to root_path
  end

  def channel_params
    params.require(:channel).permit(:channel_main_image, :name, :identification, :password, :password_confirmation, :channel_background_image,
                                    :introduction)
  end
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/views/channels/edit.html.erb
<%# チャンネル ログアウト モーダル Start %>
<%= render "shared/channel_left_modal" %>
<%# チャンネル ログアウト モーダル End %>

<%# チャンネル 共通 Start %>
<div class = "channel">

  <%# チャンネル ナビゲーション Start %>
  <%= render "shared/channel_left" %>
  <%# チャンネル ナビゲーション End %>

  <%# チャンネル編集 Start %>
  <div class = "channel-right">

    <%# チャンネル編集フォーム Start %>
    <div class = "form-left">
      <%= form_with model:@channel, local: true do |f| %>
      
        <%# チャンネル編集フォーム ヘッダー Start %>
        <div class ="form-back">
          <%= link_to '< 戻る', channel_path(params[:id]), class:"form-back-text" %>
        </div>
        <div class ="form-title-left">
        チャンネル　編集
        </div>
        <%# チャンネル編集フォーム ヘッダー End %>

        <%# チャンネル編集フォーム エラー Start %>
        <div class = "form-error-left">
          <%= render 'shared/error_messages', resource: @channel %>
        </div>
        <%# チャンネル編集フォーム エラー End %>

        <%# チャンネル編集フォーム 画像・名前 Start %>
        <div class= "form-beside">
          <div class="form-beside-field">
            <% f.label :image,class:"form-field-label" %>
            <div class = "form-field-firstimage">
              <%= f.file_field :channel_main_image, class:"form-field-firstimage-image" %>
              <span class="form-field-firstimage-custom", id="channel-main-image"></span>
              <%= image_tag 'channel/index/photo-button.png',class:"form-field-firstimage-button" %>
            </div>
          </div>
          <div class="form-beside-field">
            <%= f.label :name, "チャンネル名",class:"form-field-label" %><br />
            <%= f.text_field :name, placeholder:"チャンネル名を入力してください", autofocus: true, autocomplete: "name",class:"form-field-string-name" %>
          </div>
        </div>
        <%# チャンネル編集フォーム 画像・名前 End %>

        <%# チャンネル編集フォーム その他 Start %>
        <div class = "form-vertical">
          <div class = "form-vertical-field">
            <%= f.label :identification, "ID",class:"form-field-label" %>
            <%= f.text_field :identification, placeholder:"IDを入力してください", autocomplete: "identification", class:"form-field-string" %>
          </div>
          <div class="form-vertical-field">
            <%= f.label :password, "パスワード",class:"form-field-label" %>
            <%= f.password_field :password, placeholder:"パスワードを入力してください", autocomplete: "new-password", class:"form-field-string" %>
          </div>
          <div class="form-vertical-field">
            <%= f.label :password_confirmation, "確認用",class:"form-field-label" %>
            <%= f.password_field :password_confirmation, placeholder:"確認のため、もう一度パスワードを入力してください", autocomplete: "new-password", class:"form-field-string" %>
          </div>
          <div class="form-vertical-field">
            <%= f.label :channel_background_image, "背景画像",class:"form-field-label" %>
            <div class = "form-field-secondimage">
              <%= f.file_field :channel_background_image, class:"form-field-secondimage-image" %>
              <span class="form-field-secondimage-custom", id="channel-backgroundimage-image"></span>
              <%= image_tag 'channel/index/photo-button.png',class:"form-field-secondimage-button" %>
            </div>
          </div>
          <div class="form-vertical-field">
            <%= f.label :introduction, "紹介文",class:"form-field-label" %>
            <%= f.text_area :introduction, placeholder:"紹介文を入力してください", autocomplete: "profile",class:"form-field-text" %>
          </div>
          <div class="form-vertical-field">
            <%= f.label :administrator, "管理者",class:"form-field-label" %>
            <div class = "form-field-users">
              <% @users.each do |administrator| %>
                <div class="form-field-user">
                  <% checked = @channel.channel_users.exists?(user_id: administrator.id, administrator: true) %>
                  <%= check_box_tag 'administrators[]', administrator.id, checked, class: "form-field-user-check", id: "administrator_#{administrator.id}" %>
                    <%= image_tag administrator.profile_image.presence || 'common/noimage.png', class:"form-field-user-image" %>
                  <%= label_tag "administrator_#{administrator.id}", administrator.name, class: "form-field-user-name" %>
                </div>
              <% end %>
            </div>
          </div>
          <div class="form-vertical-field">
            <%= f.label :user, "参加者",class:"form-field-label" %>
            <div class = "form-field-users">
              <% @users.each do |user| %>
                <div class="form-field-user">
                  <% checked = @channel.channel_users.exists?(user_id: user.id, administrator: false) %>
                  <%= check_box_tag "users[]", user.id, checked, class: "form-field-user-check", id: "user_#{user.id}" %>
                    <%= image_tag user.profile_image.presence || 'common/noimage.png', class:"form-field-user-image" %>
                  <%= label_tag "user_#{user.id}", user.name, class: "form-field-user-name" %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
        <%# チャンネル編集フォーム その他 End %>

        <%# チャンネル編集フォーム アクション Start %>
        <div class="form-action">
          <%= f.submit "更新する",class:"form-action-submit"%>
          <div class="form-action-delete">
          削除する
          </div>

          <%# チャンネル編集フォーム チャンネル削除 モーダル Start %>
          <div class ="modal" id = "modal-channel-delete">
            <div class= "modal-box">
              <div class ="modal-box-title">
                本当に削除しますか？
              </div>
              <div class ="modal-actions">
                <%= link_to 'Yes', channel_path(@channel.id), data: { turbo_method: :delete }, class:"modal-actions-y" %>
                <div class ="modal-actions-n">
                  No
                </div>
              </div>
            </div>
          </div>
          <%# チャンネル編集フォーム チャンネル削除 モーダル End %>

        </div>
        <%# チャンネル編集フォーム アクション End %>

      <% end %>
    </div>
    <%# チャンネル編集フォーム END %>

  </div>
  <%# チャンネル編集 Start %>

</div>
<%# 共通 END %>

app/views/channels/index.html.erb
<%# チャンネル一覧ページ Start %>
<div class = "channel-index" >
  <div class ="channel-index-title">
    チャンネルを選択してください
  </div>
  <div class ="channel-index-lists">

    <%# 所属しているチャンネルがなかった場合 Start %>
    <% if @channels.empty? %>
      <div class = "channel-index-empty">
        <div class = "channel-index-empty-text">
          登録されているチャンネルがありません。右下の＋ボタンから新規で作成するか、チャンネルの管理者にあなたを登録いただくようお願いいたします。
        </div>
      </div>
    <%# 所属しているチャンネルがなかった場合 End %>

    <%# 所属しているチャンネルがあった場合 Start %>
    <% else %>
      <% @channels.each do |channel| %>
        <div class ="channel-index-list">
          <%= image_tag(channel.channel_main_image.presence || 'common/noimage.png', class:"channel-index-list-image") %>
          <div class ="channel-index-list-title">
            <%= channel.name %>
          </div>
        </div>

        <%# チャンネル一覧ページ チャンネルログイン モーダル Start %>
        <div class="overlay"></div>
        <div class= "modal" id = "modal-channel-login" >
          <div class= "modal-back">
            ×
          </div>
          <div class= "modal-box">
            <%= form_with model: @session, url:sessions_path, local: true, method: :post do |f| %>
              <%= f.hidden_field :channel_id, value: channel.id %>
              <div class ="modal-box-title">
                <%= channel.name %>
              </div>
              <div class ="modal-box-field">
                <div class ="modal-box-field-label">
                  ID
                </div>
                <%= f.text_field:identification, placeholder: "IDを入力してください", class:"modal-box-field-string" %>
              </div>
              <div class ="modal-box-field">
                <div class ="modal-box-field-label">
                  パスワード
                </div>
                <%= f.password_field:password, placeholder: "パスワードを入力してください" ,class:"modal-box-field-string"%>
              </div>
              <%= f.submit "参加する" ,class:"modal-box-submit"%>
            <% end %>
          </div>
        </div>
        <%# チャンネル一覧ページ チャンネルログイン モーダル End %>
        
      <% end %>
    <% end %>
    <%# 所属しているチャンネルがあった場合 End %>

  </div>
  <%= button_to 'ログアウト', destroy_user_session_path, method: :delete ,class:"channel-index-empty-logout"%>
  <%= link_to '+' ,new_channel_path ,class:"channel-index-new" %>
</div>
<%# チャンネル一覧ページ End %>

app/views/channels/new.html.erb
<%# 新規チャンネル作成 Start %>
<div class = "form-center">

  <%# 新規チャンネル作成フォーム Start %>
  <%= form_with model:@channel, local: true do |f| %>
    
    <%# 新規チャンネル作成フォーム ヘッダー Start %>
    <div class ="form-back">
      <%= link_to '< 戻る', root_path, class:"form-back-text" %>
    </div>
    <div class ="form-title-center">
    チャンネル　新規作成
    </div>
    <%# 新規チャンネル作成フォーム ヘッダー End %>

    <%# 新規チャンネル作成フォーム エラー Start %>
    <div class = "form-error-center">
      <%= render 'shared/error_messages', resource: @channel %>
    </div>
    <%# 新規チャンネル作成フォーム エラー End %>

    <%# 新規チャンネル作成フォーム 画像・名前 Start %>
    <div class= "form-beside">
      <div class="form-beside-field">
        <% f.label :channel_main_image,class:"form-field-label" %>
        <div class = "form-field-firstimage">
          <%= f.file_field :channel_main_image, class:"form-field-firstimage-image" %>
          <span class="form-field-firstimage-custom", id="channel-main-image"></span>
          <%= image_tag 'channel/index/photo-button.png',class:"form-field-firstimage-button" %>
        </div>
      </div>
      <div class="form-beside-field">
        <%= f.label :name, "チャンネル名",class:"form-field-label" %><br />
        <%= f.text_field :name, placeholder:"チャンネル名を入力してください", autofocus: true, autocomplete: "name",class:"form-field-string-name" %>
      </div>
    </div>
    <%# 新規チャンネル作成フォーム 画像・名前 End %>

    <%# 新規チャンネル作成フォーム その他 Start %>
    <div class = "form-vertical">
      <div class = "form-vertical-field">
        <%= f.label :identification, "ID",class:"form-field-label" %>
        <%= f.text_field :identification, placeholder:"IDを入力してください", autocomplete: "identification", class:"form-field-string" %>
      </div>
      <div class="form-vertical-field">
        <%= f.label :password, "パスワード",class:"form-field-label" %>
        <%= f.password_field :password, placeholder:"パスワードを入力してください", autocomplete: "new-password", class:"form-field-string" %>
      </div>
      <div class="form-vertical-field">
        <%= f.label :password_confirmation, "確認用",class:"form-field-label" %>
        <%= f.password_field :password_confirmation, placeholder:"確認のため、もう一度パスワードを入力してください", autocomplete: "new-password", class:"form-field-string" %>
      </div>
      <div class="form-vertical-field">
        <%= f.label :channel_background_image, "背景画像",class:"form-field-label" %>
        <div class = "form-field-secondimage">
          <%= f.file_field :channel_background_image, class:"form-field-secondimage-image" %>
          <span class="form-field-secondimage-custom", id="channel-backgroundimage-image"></span>
          <%= image_tag 'channel/index/photo-button.png',class:"form-field-secondimage-button" %>
        </div>
      </div>
      <div class="form-vertical-field">
        <%= f.label :introduction, "紹介文",class:"form-field-label" %>
        <%= f.text_area :introduction, placeholder:"紹介文を入力してください", autocomplete: "profile",class:"form-field-text" %>
      </div>
      <div class="form-vertical-field">
        <%= f.label :administrator, "管理者",class:"form-field-label" %>
        <div class = "form-field-users">
          <% @users.each do |administrator| %>
            <div class="form-field-user">
              <%= check_box_tag 'administrators[]', administrator.id, false, class: "form-field-user-check", id: "administrator_#{administrator.id}" %>
                <%= image_tag administrator.profile_image.presence || 'common/noimage.png', class:"form-field-user-image" %>
              <%= label_tag "administrator_#{administrator.id}", administrator.name, class: "form-field-user-name" %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="form-vertical-field">
        <%= f.label :user, "参加者",class:"form-field-label" %>
        <div class = "form-field-users">
          <% @users.each do |user| %>
            <div class="form-field-user">
              <%= check_box_tag "users[]", user.id, false, class: "form-field-user-check", id: "user_#{user.id}" %>
                <%= image_tag user.profile_image.presence || 'common/noimage.png', class:"form-field-user-image" %>
              <%= label_tag "user_#{user.id}", user.name, class: "form-field-user-name" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <%# 新規チャンネル作成フォーム その他 End %>

    <%# 新規チャンネル作成フォーム アクション Start %>
    <div class="form-action">
      <%= f.submit "作成する",class:"form-action-submit"%>
    </div>
    <%# 新規チャンネル作成フォーム アクション End %>

  <% end %>
  <%# 新規チャンネル作成フォーム End %>

</div>
<%# 新規チャンネル作成 End %>

app/views/channels/show.html.erb
<%# チャンネル ログアウト モーダル Start %>
<%= render "shared/channel_left_modal" %>
<%# チャンネル ログアウト モーダル End %>

<%# チャンネル 共通 Start %>
<div class = "channel">

  <%# チャンネル ナビゲーション Start %>
  <%= render "shared/channel_left" %>
  <%# チャンネル ナビゲーション End %>

  <%# チャンネル詳細ページ  Start %>
  <div class = "channel-right">
    <div class = "channel-show">

      <%# チャンネル詳細ページ ヘッダー Start %>
      <div class = "channel-show-top">
        <%= image_tag @channel.channel_background_image.presence || 'common/noimage.png', class:"channel-show-top-background" %>
        <div class ="channel-show-top-channel">
          <%= image_tag @channel.channel_main_image.presence || 'common/noimage.png' ,class: "channel-show-top-channel-image" %>
          <div class ="channel-show-top-channel-name">
            <%= @channel.name %>
          </div>
          <div class= "channel-show-top-channel-id">
            <%= @channel.identification %>
          </div>
        </div>
        <% if @channel.administrators.include?(current_user) %>
          <%= link_to "編集", edit_channel_path(@channel.id) ,class:"channel-show-top-channel-edit" %>
        <% end %>
      </div>
      <%# チャンネル詳細ページ ヘッダー End %>

      <%# チャンネル詳細ページ 各コンテンツ一覧 Start %>
      <div class ="channel-show-buttom">
        <div class ="channel-show-buttom-profile">
          <%= image_tag 'channel/index/profile.svg',class:"channel-show-buttom-profile-image" %>
          <div class = "channel-show-buttom-profile-content">
            <div class = "channel-show-buttom-title">
              紹介文
            </div>
            <div class ="channel-show-buttom-text">
              <%= @channel.introduction %>
            </div>
          </div>
        </div>
        <div class ="channel-show-buttom-administrator">
          <div class ="channel-show-buttom-title">
            管理者
          </div>
          <ul class = "channel-show-buttom-users">
            <% @administrators.each do |administrator| %>
              <li class ="channel-show-buttom-user">
                <%= link_to user_path(administrator) do %>
                  <%= image_tag administrator.profile_image.presence || 'common/noimage.png', class:"channel-show-buttom-user-image" %>
                  <div class ="channel-show-buttom-user-name">
                    <%= administrator.name %>
                  </div>
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
        <div class ="channel-show-buttom-participant">
          <div class ="channel-show-buttom-title">
            参加者
          </div>
          <ul class = "channel-show-buttom-users">
            <% @channel_users.each do |user| %>
              <li class ="channel-show-buttom-user">
                <%= link_to user_path(user.user.id) do %>
                  <%= image_tag user.user.profile_image.presence || 'common/noimage.png', class:"channel-show-buttom-user-image" %>
                  <div class ="channel-show-buttom-user-name">
                    <%= user.user.name %>
                  </div>
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
        <div class ="channel-show-buttom-event">
          <div class ="channel-show-buttom-title">
            イベント
          </div>
          <ul class ="channel-show-buttom-event-lists">
            <% @events.each do |event| %>
              <%= link_to channel_event_path(@channel,event) do %>
                <li class ="channel-show-buttom-event-list">
                  <div class ="channel-show-buttom-event-list-date">
                    <%= event.date_start.strftime('%Y年%m月%d日') + '(' + %w(日 月 火 水 木 金 土)[event.date_start.wday] + ')' %>
                  </div>
                  <div class ="channel-show-buttom-event-list-name">
                    <%= event.name %>
                  </div>
                </li>
              <% end %>
            <% end %>
          </ul>
        </div>
        <div class ="channel-show-buttom-topics">
          <div class ="channel-show-buttom-title">
            News&Topics
          </div>
          <ul class ="channel-show-buttom-topics-lists">
            <% @topics.each do |topic| %>
              <li class ="channel-show-buttom-topics-list">
                <div class ="channel-show-buttom-topics-list-left">
                  <%= image_tag topic.channel_user.user.profile_image.presence || 'common/noimage.png', class:"channel-show-buttom-topics-list-left-image" %>
                </div>
                <div class ="channel-show-buttom-topics-list-right">
                  <div class ="channel-show-buttom-topics-list-right-top">
                    <div class ="channel-show-buttom-topics-list-right-top-name">
                      <%= topic.channel_user.user.name %>
                    </div>
                    <div class ="channel-show-buttom-topics-list-right-top-time">
                      <%= topic.created_at.strftime('%Y年%m月%d日') + '(' + %w(日 月 火 水 木 金 土)[topic.created_at.wday] + ')' %>
                    </div>
                  </div>
                  <div class ="channel-show-buttom-topics-list-right-center">
                    <div class ="channel-show-buttom-topics-list-right-center-title">
                      <%= topic.title %>
                    </div>
                    <% if topic.channel_user.user == current_user %>
                      <div class ="channel-show-buttom-topics-list-right-center-actions">
                        <%= link_to "編集", edit_channel_topic_path(@channel.id, topic) ,class:"channel-show-buttom-topics-list-right-center-actions-edit" %>
                        <div class ="channel-show-buttom-topics-list-right-center-actions-delete">
                          削除
                        </div>

                        <%# チャンネル詳細ページ チャンネル削除 モーダル Start %>
                        <div class ="modal" id="modal-show-topics-delete">
                          <div class= "modal-box">
                            <div class ="modal-box-title">
                              本当に削除しますか？
                            </div>
                            <div class ="modal-actions">
                              <%= link_to 'Yes', channel_topic_path(@channel.id,topic), data: { turbo_method: :delete }, class:"modal-actions-y" %>
                              <div class ="modal-actions-n">
                                No
                              </div>
                            </div>
                          </div>
                        </div>
                        <%# チャンネル詳細ページ チャンネル削除 モーダル End %>

                      </div>
                    <% end %>
                  </div>
                  <div class ="channel-show-buttom-topics-list-right-buttom">
                    <%= topic.text %>
                  </div>
                  <div class ="channel-show-buttom-topics-list-right-line">
                  </div>
                </div>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
      <%# ユーザー詳細ページ 各コンテンツ一覧 Start %>

    </div>
  </div>
  <%# チャンネル詳細ページ  End %>

</div>
<%# チャンネル 共通 Start %>