config/routes.rb
Rails.application.routes.draw do
  root to: 'channels#index'
  devise_for :users
  resources :channels do
    resources :tweets, only: [:index, :show, :create]
    resources :chats do
      resource :messages, only: [:create]
    end
    resources :events do
      resources :channel_event_users, only: [:create, :destroy]
    end
    resources :albums
    resources :topics, only: [:new ,:create,  :edit ,:update ,:destroy] 
  end
  resource :sessions, only: [:index, :new, :create, :destroy]
  resources :users, only: [:show, :edit ,:update, :destroy]
end

app/models/age.rb
class Age < ActiveHash::Base
  self.data = [{ id: 1, name: '---' }, { id: 2, name: '18歳' }, { id: 3, name: '19歳' }, { id: 4, name: '20歳' },
               { id: 5, name: '21歳' }, { id: 6, name: '22歳' }, { id: 7, name: '23歳' }, { id: 8, name: '24歳' }, { id: 9, name: '25歳' }, { id: 10, name: '26歳' }, { id: 11, name: '27歳' }, { id: 12, name: '28歳' }, { id: 13, name: '29歳' }, { id: 14, name: '30歳' }, { id: 15, name: '31歳' }, { id: 16, name: '32歳' }, { id: 17, name: '33歳' }, { id: 18, name: '34歳' }, { id: 19, name: '35歳' }, { id: 20, name: '36歳' }, { id: 21, name: '37歳' }, { id: 22, name: '38歳' }, { id: 23, name: '39歳' }, { id: 24, name: '40歳' }, { id: 25, name: '41歳' }, { id: 26, name: '42歳' }, { id: 27, name: '43歳' }, { id: 28, name: '44歳' }, { id: 29, name: '45歳' }, { id: 30, name: '46歳' }, { id: 31, name: '47歳' }, { id: 32, name: '48歳' }, { id: 33, name: '49歳' }, { id: 34, name: '50歳' }, { id: 35, name: '51歳' }, { id: 36, name: '52歳' }, { id: 37, name: '53歳' }, { id: 38, name: '54歳' }, { id: 39, name: '55歳' }, { id: 40, name: '56歳' }, { id: 41, name: '57歳' }, { id: 42, name: '58歳' }, { id: 43, name: '59歳' }, { id: 44, name: '60歳' }]

  include ActiveHash::Associations
  has_many :users
end

app/models/album.rb
class Album < ApplicationRecord
  # Association
  has_many_attached :album_images

  belongs_to :channel

  # Validation
  validates :title, presence: true
end

app/models/channel.rb
class Channel < ApplicationRecord
  # Association
  has_one_attached :channel_main_image
  has_one_attached :channel_background_image

  has_secure_password

  has_many :channel_users, dependent: :destroy
  has_many :users, through: :channel_users
  has_many :administrators, -> { where(channel_users: { administrator: true }) }, through: :channel_users, source: :user
  has_many :albums, dependent: :destroy
  has_many :tweets, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_many :topics, dependent: :destroy
  has_many :events, dependent: :destroy

  # Validation
  validates :name, presence: true
  validates :identification, presence: true, uniqueness: true
  validates :password, presence: true, confirmation: true, length: { minimum: 6, maximum: 128 }, if: :password_required?
  # validates :introduction

  def password_required?
    new_record? || password.present? || password_confirmation.present?
  end
end

app/models/channel_user.rb
class ChannelUser < ApplicationRecord
  # Association
  has_many :tweets, dependent: :destroy
  has_many :channel_chat_users, dependent: :destroy
  has_many :channel_event_users, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :events, through: :channel_event_users
  has_many :topics, dependent: :destroy

  belongs_to :channel
  belongs_to :user

  def administrator?
    administrator == 1
  end

  # Validation
end

app/models/chat.rb
class Chat < ApplicationRecord
  # Association
  has_one_attached :chat_image

  has_many :channel_chat_users, dependent: :destroy
  has_many :messages

  belongs_to :channel

  # Validation
  validates :name, presence: true
end

app/models/event.rb
class Event < ApplicationRecord
  # Association
  has_one_attached :event_image

  has_many :channel_event_users, dependent: :destroy
  has_many :channel_users, through: :channel_event_users

  belongs_to :channel
  belongs_to :channel_user

  # Validation
  validates :name, presence: true
  validates :date_start, presence: true
  validates :date_end, presence: true
  validates :time_start, presence: true
  validates :time_end, presence: true
end

app/models/gender.rb
class Gender < ActiveHash::Base
  self.data = [{ id: 1, name: '---' }, { id: 2, name: '男性' }, { id: 3, name: '女性' }, { id: 4, name: 'その他' }]

  include ActiveHash::Associations
  has_many :users
end

app/models/mbti.rb
class Mbti < ActiveHash::Base
  self.data = [{ id: 1, name: '---' }, { id: 2, name: 'ENTP(討論者)' }, { id: 3, name: 'INTP(論理学者)' }, { id: 4, name: 'INTJ(建築家)' },
               { id: 5, name: 'ENTJ(指揮官)' }, { id: 6, name: 'ENFP(運動家)' }, { id: 7, name: 'INFP(仲介者)' }, { id: 8, name: 'INFJ(提唱者)' }, { id: 9, name: 'ENFJ(主人公)' }, { id: 10, name: 'ESTJ(幹部)' }, { id: 11, name: 'ISTJ(管理者)' }, { id: 12, name: 'ISFJ(擁護者)' }, { id: 13, name: 'ESFJ(領事)' }, { id: 14, name: 'ESTP(起業家)' }, { id: 15, name: 'ISTP(巨匠)' }, { id: 16, name: 'ISFP(冒険家)' }, { id: 17, name: 'ESFP(エンターテイナー)' }]

  include ActiveHash::Associations
  has_many :users
end

app/models/message.rb
class Message < ApplicationRecord
  # Association
  has_one_attached :message_image

  belongs_to :channel_chat_user
  belongs_to :chat

  # Validation
  validate :either_content_or_image

  def either_content_or_image
    return if content.present? || message_image.attached?

    errors.add(:base, 'Either text or image must be present.')
  end
end

app/models/topic.rb
class Topic < ApplicationRecord
  # Association
  belongs_to :channel
  belongs_to :channel_user

  # Validation
  validates :title, presence: true
  validates :text, presence: true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  # Association
  has_one_attached :tweet_image

  belongs_to :channel_user
  belongs_to :channel

  # Validation
  validate :either_text_or_image

  private

  def either_text_or_image
    return if text.present? || tweet_image.attached?

    errors.add(:base, 'Either text or image must be present.')
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Association
  has_one_attached :profile_image
  has_one_attached :background_image

  has_many :channel_users, dependent: :destroy
  has_many :channels, through: :channel_users

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :gender
  belongs_to :age
  belongs_to :mbti

  # Validation
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i
  VALID_ID_REGEX = /\A[a-zA-Z0-9_]+\z/

  # validates :image(profile)
  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true, length: { minimum: 6 },
                       format: { with: VALID_PASSWORD_REGEX }, on: :create
  validates :password, length: { minimum: 6 },
                       format: { with: VALID_PASSWORD_REGEX }, allow_blank: true, on: :update
  # validates :gender_id
  # validates :age_id
  # validates :birthday
  # validates :mbti_id
  validates_format_of :line, with: VALID_ID_REGEX, allow_blank: true
  validates_format_of :paypay, with: VALID_ID_REGEX, allow_blank: true
  # validates :image(background)
  # validates :profile
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Unityhub40289</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100..900&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_channel_left.erb
<%# チャンネル ナビゲーション Start %>
<div class = "channel-left">

  <%# ロゴ Start %>
  <h1 class = "logo">
    UnityHub
  </h1>
  <%# ロゴ End %>

  <%# チャンネル表示部分 Start %>
  <div class = "channel-left-channel">
    <%= image_tag(@channel.channel_main_image.presence || 'common/noimage.png', class: "channel-left-channel-image") %>
    <div class = "channel-left-channel-name">
      <%= @channel.name %>
    </div>
  </div>
  <%# チャンネル表示部分 End %>

  <%# ナビゲーション部分 Start %>
  <ul class = "channel-left-nav">
    <%= link_to channel_path(session[:channel_id]) do %>
      <li class = "channel-left-nav-list">
        <%= image_tag 'channel/index/nav-home.svg',class:"list-image" %>
        <div class = "list-text">
          ホーム
        </div>
      </li>
    <% end %>
    <%= link_to channel_tweets_path(@channel) do %>
      <li class = "channel-left-nav-list">
        <%= image_tag 'channel/index/nav-tweet.svg',class:"list-image" %>
        <div class = "list-text">
          ツイート
        </div>
      </li>
    <% end %>
    <%= link_to channel_chats_path(@channel) do %>
      <li class = "channel-left-nav-list">
        <%= image_tag 'channel/index/nav-chat.svg',class:"list-image" %>
        <div class = "list-text">
          チャット
        </div>
      </li>
    <% end %>
    <%= link_to channel_events_path(@channel) do %>
    <li class = "channel-left-nav-list">
      <%= image_tag 'channel/index/nav-calendar.svg',class:"list-image" %>
      <div class = "list-text">
        カレンダー
      </div>
    </li>
    <% end %>
    <%= link_to channel_albums_path(@channel) do %>
      <li class = "channel-left-nav-list">
        <%= image_tag 'channel/index/nav-album.svg',class:"list-image" %>
        <div class = "list-text">
          アルバム
        </div>
      </li>
    <% end %>
    <%= link_to user_path(current_user.id) do %>
      <li class = "channel-left-nav-list">
        <%= image_tag 'channel/index/nav-profile.svg',class:"list-image" %>
        <div class = "list-text">
          プロフィール
        </div>
      </li>
    <% end %>
  </ul>
  <%# ナビゲーション部分 End %>

  <%# フォーム部分 Start %>
  <ul class = "channel-left-post">
    <%= link_to new_channel_topic_path(@channel) do %>
      <li class = "channel-left-post-list">
        <%= image_tag 'channel/index/post-topics.svg',class:"list-image" %>
        <div class = "list-text">
          News&Topics
        </div>
      </li>
    <% end %>
    <%= link_to new_channel_event_path(@channel) do %>
      <li class = "channel-left-post-list">
        <%= image_tag 'channel/index/post-event.svg',class:"list-image" %>
        <div class = "list-text">
          イベント申請
        </div>
      </li>
    <% end %>
  </ul>
  <%# フォーム部分 End %>

  <%# ユーザー ログアウト Start %>
  <div class = "channel-left-logout">
    <%= image_tag 'channel/index/logout.svg',class:"list-image" %>
    <div class ="list-text">
      ログアウト
    </div>
  </div>
  <%# ユーザー ログアウト End %>

</div>
<%# チャンネル ナビゲーション End %>

app/views/shared/_channel_left_modal.html.erb
<%# ログアウト モーダル 共通 Start %>
<div class="overlay"></div>
<%# ログアウト モーダル 共通 End %>

<%# チャンネル ログアウト モーダル Start %>
<div class= "modal" id = "modal-channel-logout">
  <div class= "modal-box">
    <div class ="modal-box-title">
      チャンネルを退出しますか？
    </div>
    <div class ="modal-actions">
      <%= link_to 'Yes', root_path, class:"modal-actions-y" %>
      <div class ="modal-actions-n">
        No
      </div>
    </div>
  </div>
</div>
<%# チャンネル ログアウト モーダル End %>

<%# ユーザー ログアウト モーダル Start %>
<div class= "modal" id = "modal-user-logout">
  <div class= "modal-box">
    <div class ="modal-box-title">
      ログアウトしますか？
    </div>
    <div class ="modal-actions">
      <%= link_to 'Yes', destroy_user_session_path, data: {turbo_method: :delete}, class:"modal-actions-y" %>
      <div class ="modal-actions-n">
        No
      </div>
    </div>
  </div>
</div>
<%# チャンネル ログアウト モーダル End %>

app/views/shared/_channel_tweet.erb
<%# チャンネル ログアウト モーダル Start %>
<%= render "shared/channel_left_modal" %>
<%# チャンネル ログアウト モーダル End %>

<%# チャンネル 共通 Start %>
<div class = "channel">

  <%# チャンネル ナビゲーション Start %>
  <%= render "shared/channel_left" %>
  <%# チャンネル ナビゲーション End %>

  <%# ツイート Start %>
  <div class = "channel-right">
    <div class = "channel-tweet">
      
      <%# ツイート ユーザー選択 Start %>
      <div class ="chanel-tweet-left">
        <%= form_tag channel_tweets_path(@channel), method: :get, class: "chanel-tweet-left-search" do %>
          <%= text_field_tag :search, params[:search], placeholder: "キーワードを入力してください", class:"chanel-tweet-left-search-input" %>
            <div class = "chanel-tweet-left-search-button" >
            <%= image_submit_tag 'tweet/index/search.svg', class: "chanel-tweet-left-search-button-image" %>
          </div>
        <% end %>
        <div class ="chanel-tweet-left-users">
            <%= link_to channel_tweets_path(@channel), class:"chanel-tweet-left-user" do %>
              <%= image_tag(@channel.channel_main_image.presence || 'common/noimage.png', class: "chanel-tweet-left-user-image") %>
              <div class ="chanel-tweet-left-user-name">
                All
              </div>
          <% end %>
          <% @channel_users.each do |channel_user| %>
            <%= link_to channel_tweet_path(channel_user.channel,channel_user), class:"chanel-tweet-left-user" do %>
                <%= image_tag(channel_user.user.profile_image.presence || 'common/noimage.png', class: "chanel-tweet-left-user-image") %>
              <div class ="chanel-tweet-left-user-name">
                <%= channel_user.user.name %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
      <%# ツイート ユーザー選択 End %>

      <%# ツイート ツイート表示部分 Start %>
      <div class ="chanel-tweet-right">
        <div class ="chanel-tweet-right-tweets">
          <% @tweets.each do |tweet| %>
            <div class ="chanel-tweet-right-tweet">
                <%= image_tag(tweet.channel_user.user.profile_image.presence || 'common/noimage.png', class: "chanel-tweet-right-tweet-userimage") %>
              <div class ="chanel-tweet-right-tweet-content">
                <div class ="chanel-tweet-right-tweet-content-top">
                  <div class ="chanel-tweet-right-tweet-content-top-username">
                    <%= tweet.channel_user.user.name %>
                  </div>
                  <div class ="chanel-tweet-right-tweet-content-top-date">
                    <%= tweet.created_at.strftime('%Y年%m月%d日') + '(' + %w(日 月 火 水 木 金 土)[tweet.created_at.wday] + ')' %>
                  </div>
                </div>
                <div class ="chanel-tweet-right-tweet-content-text">
                  <%= tweet.text %>
                </div>
                <div class ="chanel-tweet-right-tweet-content-buttom">
                  <% if tweet.tweet_image.attached? %>
                    <%= image_tag(tweet.tweet_image, class: "chanel-tweet-right-tweet-content-buttom-image") %>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      <%# ツイート ツイート表示部分 End %>

    </div>
  </div>
  <%# ツイート End %>

</div>
<%# チャンネル 共通 End %>

<%# ツイート 新規投稿 Start %>
<div class ="channel-tweet-action" >
  +
</div>
<%# ツイート 新規投稿 End %>

<%# ツイート 新規投稿 モーダル Start %>
<div class ="modal" id ="modal-tweet-new">
  <div class= "modal-back">
    ×
  </div>
  <div class= "modal-box">
    <%= form_with model:[@channel, @tweet], local: true do |f| %>
      <div class = "modal-box-error">
        <%= render "shared/error_messages", resource: @channel %>
      </div>
      <%= f.text_area :text, placeholder:"投稿文を入力してください", autocomplete: "text",class:"modal-box-text" %>
      <div class ="modal-box-buttom">
        <div class ="modal-box-buttom-image">
          <div class ="modal-box-buttom-image-button">
            <div class ="modal-box-buttom-image-button-plus">
              +
            </div>
            <div class ="modal-box-buttom-image-button-add">
              Add
            </div>
          </div>
          <%= f.file_field :tweet_image, class:"modal-box-buttom-image-input" %>
          <span class="modal-box-buttom-image-input-custom", id="tweet-image"></span>
        </div>
        <%= image_submit_tag 'tweet/index/tweet.svg', class: "modal-box-buttom-botton-image",id: "tweet-submit" %>
      </div>
    <% end %>
  </div>
</div>
<%# ツイート 新規投稿 モーダル End %>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: '<'), calendar.url_for_previous_view ,class:"calendar-heading-button" %>
    <div class="calendar-title">
      <div class="calendar-title-year">
        <%= start_date.year %>
      </div>
      <div class="calendar-title-month">
        <%= I18n.with_locale(:en) { t('date.month_names')[start_date.month] } %>
      </div>
    </div>
    <%= link_to t('simple_calendar.next', default: '>'), calendar.url_for_next_view ,class:"calendar-heading-button"%>
  </div>

  <table class="table-table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th class ="table-table-striped-week"><%= I18n.with_locale(:en) {t('date.abbr_day_names')[day.wday]} %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>