config/routes.rb
Rails.application.routes.draw do
  root to: 'channels#index'
  devise_for :users
  resources :channels do
    resources :tweets, only: [:index, :show, :create]
    resources :chats do
      resource :messages, only: [:create]
    end
    resources :events do
      resources :channel_event_users, only: [:create, :destroy]
    end
    resources :albums
    resources :topics, only: [:new ,:create,  :edit ,:update ,:destroy] 
  end
  resource :sessions, only: [:index, :new, :create, :destroy]
  resources :users, only: [:show, :edit ,:update, :destroy]
end

app/models/event.rb
class Event < ApplicationRecord
  # Association
  has_one_attached :event_image

  has_many :channel_event_users, dependent: :destroy
  has_many :channel_users, through: :channel_event_users

  belongs_to :channel
  belongs_to :channel_user

  # Validation
  validates :name, presence: true
  validates :date_start, presence: true
  validates :date_end, presence: true
  validates :time_start, presence: true
  validates :time_end, presence: true
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_channel, only: [:index, :new, :create, :edit, :update, :show, :destroy]
  before_action :set_event, only: [:edit, :update, :show, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :set_channel_users, only: [:new, :create, :edit, :update]

  def index
    if params[:date]
      @date = Date.parse(params[:date])
      @events = @channel.events.where(date_start: @date.beginning_of_day..@date.end_of_day)
    else
      @events = @channel.events
    end
  end

  def new
    @event = Event.new
  end

  def create
    current_channel_user = ChannelUser.find_by(user_id: current_user.id)
    @event = @channel.events.build(event_params.merge(channel_user: current_channel_user))
    if @event.save
      (params[:users] || []).each do |user_id|
        channel_user = ChannelUser.find_by(user_id: user_id, channel_id: @channel.id)
        @event.channel_event_users.create(channel_user_id: channel_user.id) if channel_user
      end
      redirect_to channel_event_path(@event.channel, @event)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @event.update(event_params)
      @event.channel_event_users.destroy_all
      (params[:users] || []).each do |user_id|
        channel_user = ChannelUser.find_by(user_id: user_id, channel_id: @channel.id)
        @event.channel_event_users.create(channel_user_id: channel_user.id) if channel_user
      end
      redirect_to channel_event_path(params[:id])
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def show
    @channel_event_users = @event.channel_event_users
  end

  def destroy
    @event.destroy
    redirect_to channel_path(@channel)
  end

  private

  def set_channel
    @channel = Channel.find(session[:channel_id])
  end

  def set_event
    @event = @channel.events.find(params[:id])
  end

  def correct_user
    @channel = Channel.find(session[:channel_id])
    redirect_to channel_path(@channel) unless @event.channel_user.user == current_user
  end

  def set_channel_users
    @channel_users = @channel.channel_users
  end

  def event_params
    params.require(:event).permit(:name, :date_start, :date_end, :time_start, :time_end, :place,
                                  :detail).merge(channel_id: @channel.id)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/edit.html.erb
<%# チャンネル ログアウト モーダル Start %>
<%= render "shared/channel_left_modal" %>
<%# チャンネル ログアウト モーダル End %>

<%# チャンネル 共通 Start %>
<div class = "channel">

  <%# チャンネル ナビゲーション Start %>
  <%= render "shared/channel_left" %>
  <%# チャンネル ナビゲーション End %>

  <%# イベント 編集 Start %>
  <div class = "channel-right">

    <%# イベント 編集フォーム Start %>
    <div class = "form-left">
      <%= form_with(model:[@channel ,@event], local: true) do |f| %>

        <%# イベント 編集フォーム ヘッダー Start %>
        <div class ="form-back">
          <%= link_to '< 戻る', :back, class:"form-back-text" %>
        </div>
        <div class ="form-title-left">
          イベント　編集
        </div>
        <%# イベント 編集フォーム ヘッダー End %>

        <%# イベント 編集フォーム エラー表示 Start %>
        <div class = "form-error-left">
          <%= render 'shared/error_messages', resource: @event %>
        </div>
        <%# イベント 編集フォーム エラー表示 End %>

        <%# イベント 編集フォーム 入力部分 Start %>
        <div class = "form-vertical">
          <div class = "form-vertical-field">
            <%= f.label :name, "イベント名",class:"form-field-label" %>
            <%= f.text_field :name, placeholder:"イベント名を入力してください", autocomplete: "name", class:"form-field-string" %>
          </div>
          <div class = "form-vertical-field">
            <%= f.label :date_start, "日時",class:"form-field-label" %>
            <%= f.date_field :date_start, placeholder:"開始日を選択してください", autocomplete: "date_start", class:"form-field-date" %>
            <div class="form-field-kara">
              ~
            </div>
            <% f.label :date_end, "日時",class:"form-field-label" %>
            <%= f.date_field :date_end, placeholder:"終了日を選択してください", autocomplete: "date_end", class:"form-field-date" %>
          </div>
          <div class = "form-vertical-field">
            <%= f.label :time_start, "時刻",class:"form-field-label" %>
            <%= f.time_field :time_start, placeholder:"開始日を選択してください", autocomplete: "time_start", class:"form-field-time" %>
            <div class="form-field-kara">
              ~
            </div>
            <% f.label :time_end, "日時",class:"form-field-label" %>
            <%= f.time_field :time_end, placeholder:"終了日を選択してください", autocomplete: "time_end", class:"form-field-time" %>
          </div>
          <div class = "form-vertical-field">
            <%= f.label :place, "場所",class:"form-field-label" %>
            <%= f.text_field :place, placeholder:"場所を入力してください", autocomplete: "place", class:"form-field-string" %>
          </div>
          <div class="form-vertical-field">
            <%= f.label :user, "参加者",class:"form-field-label" %>
            <div class = "form-field-users">
              <% @channel_users.each do |channel_user| %>
                <div class="form-field-user">
                  <% checked = @event.channel_event_users.exists?(channel_user_id: channel_user.id) %>
                  <%= check_box_tag "users[]", channel_user.user.id, checked, class: "form-field-user-check", id: "user_#{channel_user.id}" %>
                    <%= image_tag channel_user.user.profile_image.presence || 'common/noimage.png', class:"form-field-user-image" %>
                  <%= label_tag "user_#{channel_user.id}", channel_user.user.name, class: "form-field-user-name" %>
                </div>
              <% end %>
            </div>
          </div>
          <div class="form-vertical-field">
            <%= f.label :detail, "詳細",class:"form-field-label" %>
            <%= f.text_area :detail, placeholder:"詳細を入力してください", autocomplete: "detail",class:"form-field-text" %>
          </div>
        </div>
        <%# イベント 編集フォーム 入力部分 End %>

        <%# イベント 編集フォーム アクション Start %>
        <div class="form-action">
          <%= f.submit "更新する",class:"form-action-submit"%>
          <div class="form-action-delete">
            削除する
          </div>

          <%# イベント 編集フォーム イベント削除 モーダル Start %>
          <div class ="modal" id = "modal-event-delete">
            <div class= "modal-box">
              <div class ="modal-box-title">
                本当に削除しますか？
              </div>
              <div class ="modal-actions">
                <%= link_to 'Yes', channel_event_path(@event.id), data: { turbo_method: :delete }, class:"modal-actions-y" %>
                <div class ="modal-actions-n">
                  No
                </div>
              </div>
            </div>
          </div>
          <%# イベント 編集フォーム イベント削除 モーダル End %>

        </div>
        <%# イベント 編集フォーム アクション End %>
        
      <% end %>
    </div>
    <%# イベント 編集フォーム End %>

  </div>
  <%# イベント 編集 End %>

</div>
<%# チャンネル 共通 End %>

app/views/events/index.html.erb
<%# チャンネル ログアウト モーダル Start %>
<%= render "shared/channel_left_modal" %>
<%# チャンネル ログアウト モーダル End %>

<%# チャンネル 共通 Start %>
<div class = "channel">

  <%# チャンネル ナビゲーション Start %>
  <%= render "shared/channel_left" %>
  <%# チャンネル ナビゲーション End %>

  <%# カレンダー Start %>
  <div class = "channel-right">
    <div class = "channel-event">
      <%= month_calendar events: @events, attribute: :date_start do |date, events| %>
        <%= date.day %>
        <% events.each do |event| %>
          <%= link_to channel_event_path(event.channel, event) do %>
            <div class ="channel-event-list">
              <%= event.name %>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
  <%# カレンダー End %>

</div>

<%# イベント 新規作成 Start %>
<%= link_to "+", new_channel_event_path(@channel) ,class:"channel-event-action" %>
<%# イベント 新規作成 End %>

app/views/events/new.html.erb
<%# チャンネル ログアウト モーダル Start %>
<%= render "shared/channel_left_modal" %>
<%# チャンネル ログアウト モーダル End %>

<%# チャンネル 共通 Start %>
<div class = "channel">

  <%# チャンネル ナビゲーション Start %>
  <%= render "shared/channel_left" %>
  <%# チャンネル ナビゲーション End %>

  <%# イベント 新規作成 Start %>
  <div class = "channel-right">

    <%# イベント 新規作成フォーム Start %>
    <div class = "form-left">
      <%= form_with(model:[@channel ,@event], local: true) do |f| %>

        <%# イベント 新規作成フォーム ヘッダー Start %>
        <div class ="form-back">
          <%= link_to '< 戻る', :back, class:"form-back-text" %>
        </div>
        <div class ="form-title-left">
          イベント申請
        </div>
        <%# イベント 新規作成フォーム ヘッダー End %>

        <%# イベント 新規作成フォーム エラー表示 Start %>
        <div class = "form-error-left">
          <%= render 'shared/error_messages', resource: @event %>
        </div>
        <%# イベント 新規作成フォーム エラー表示 End %>

        <%# イベント 新規作成フォーム 入力部分 Start %>
        <div class = "form-vertical">
          <div class = "form-vertical-field">
            <%= f.label :name, "イベント名",class:"form-field-label" %>
            <%= f.text_field :name, placeholder:"イベント名を入力してください", autocomplete: "name", class:"form-field-string" %>
          </div>
          <div class = "form-vertical-field">
            <%= f.label :date_start, "日時",class:"form-field-label" %>
            <%= f.date_field :date_start, placeholder:"開始日を選択してください", autocomplete: "date_start", class:"form-field-date" %>
            <div class="form-field-kara">
              ~
            </div>
            <% f.label :date_end, "日時",class:"form-field-label" %>
            <%= f.date_field :date_end, placeholder:"終了日を選択してください", autocomplete: "date_end", class:"form-field-date" %>
          </div>
          <div class = "form-vertical-field">
            <%= f.label :time_start, "時刻",class:"form-field-label" %>
            <%= f.time_field :time_start, placeholder:"開始日を選択してください", autocomplete: "time_start", class:"form-field-time" %>
            <div class="form-field-kara">
              ~
            </div>
            <% f.label :time_end, "日時",class:"form-field-label" %>
            <%= f.time_field :time_end, placeholder:"終了日を選択してください", autocomplete: "time_end", class:"form-field-time" %>
          </div>
          <div class = "form-vertical-field">
            <%= f.label :place, "場所",class:"form-field-label" %>
            <%= f.text_field :place, placeholder:"場所を入力してください", autocomplete: "place", class:"form-field-string" %>
          </div>
          <div class="form-vertical-field">
            <%= f.label :user, "参加者",class:"form-field-label" %>
            <div class = "form-field-users">
              <% @channel_users.each do |channel_user| %>
                <div class="form-field-user">
                  <%= check_box_tag "users[]", channel_user.user.id, false, class: "form-field-user-check", id: "user_#{channel_user.id}" %>
                    <%= image_tag channel_user.user.profile_image.presence || 'common/noimage.png', class:"form-field-user-image" %>
                  <%= label_tag "user_#{channel_user.id}", channel_user.user.name, class: "form-field-user-name" %>
                </div>
              <% end %>
            </div>
          </div>
          <div class="form-vertical-field">
            <%= f.label :detail, "詳細",class:"form-field-label" %>
            <%= f.text_area :detail, placeholder:"詳細を入力してください", autocomplete: "detail",class:"form-field-text" %>
          </div>
        </div>
        <%# イベント 新規作成フォーム 入力部分 End %>

        <%# イベント 新規作成フォーム アクション Start %>
        <div class="form-action">
          <%= f.submit "作成する",class:"form-action-submit"%>
        </div>
         <%# イベント 新規作成フォーム アクション End %>
         
      <% end %>
    </div>
    <%# イベント 新規作成フォーム End %>

  </div>
  <%# イベント 新規作成 End %>

</div>
<%# チャンネル 共通 End %>

app/views/events/show.html.erb
<%# チャンネル ログアウト モーダル Start %>
<%= render "shared/channel_left_modal" %>
<%# チャンネル ログアウト モーダル End %>

<%# チャンネル 共通 Start %>
<div class = "channel">

  <%# チャンネル ナビゲーション Start %>
  <%= render "shared/channel_left" %>
  <%# チャンネル ナビゲーション End %>

  <%# イベント詳細ページ Start %>
  <div class = "channel-right">
    <div class = "channel-event">

      <%# イベント詳細ページ ヘッダー Start %>
      <div class ="channel-event-back">
        <%= link_to '< 戻る', :back %>
      </div>
      <div class ="channel-event-title">
        <div class ="channel-event-title-name">
          <%= @event.name %>
        </div>
        <% if @event.channel_user.user == current_user %>
          <%= link_to "編集", edit_channel_event_path(@event.id) ,class:"channel-event-title-edit" %>
        <% end %>
      </div>
      <div class ="channel-event-updated">
        最終更新日：<%= @event.updated_at.strftime('%Y年%m月%d日') + '(' + %w(日 月 火 水 木 金 土)[@event.updated_at.wday] + ')' %>
      </div>
      <div class ="channel-event-line">
      </div>
      <%# イベント詳細ページ ヘッダー End %>

      <%# イベント詳細ページ 詳細 Start %>
      <div class ="channel-event-item">
        <div class ="channel-event-item-name">
          日時
        </div>
        <div class ="channel-event-item-output">
          <% if @event.date_start == @event.date_end %>
            <%= @event.date_start.strftime("%Y年%m月%d日（#{%w(日 月 火 水 木 金 土)[@event.date_start.wday]}）") %>
          <% else %>
            <%= @event.date_start.strftime("%Y年%m月%d日（#{%w(日 月 火 水 木 金 土)[@event.date_start.wday]}）") %> 〜 <%= @event.date_end.strftime("%Y年%m月%d日（#{%w(日 月 火 水 木 金 土)[@event.date_end.wday]}）") %>
          <% end %>
        </div>
      </div>
      <div class ="channel-event-item">
        <div class ="channel-event-item-name">
          時刻
        </div>
        <div class ="channel-event-item-output">
          <%= @event.time_start.strftime("%H:%M") %> 〜 <%= @event.time_end.strftime("%H:%M") %>
        </div>
      </div>
      <div class ="channel-event-item">
        <div class ="channel-event-item-name">
          場所
        </div>
        <div class ="channel-event-item-output">
          <%= @event.place %>
        </div>
      </div>
      <div class ="channel-event-item">
        <div class ="channel-event-item-name">
          参加者
        </div>
        <ul class = "channel-event-item-users">
          <% @channel_event_users.each do |channel_event_user| %>
            <li class ="channel-event-item-user">
              <%= link_to user_path(channel_event_user.channel_user.user.id) do %>
                  <%= image_tag channel_event_user.channel_user.user.profile_image.presence || 'common/noimage.png', class:"channel-event-item-user-image" %>
                <div class ="channel-event-item-users-name">
                  <%= channel_event_user.channel_user.user.name %>
                </div>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
      <div class ="channel-event-item">
        <div class ="channel-event-item-name">
          詳細
        </div>
        <div class ="channel-event-item-output">
          <%= @event.detail %>
        </div>
      </div>
      <%# イベント詳細ページ 詳細 End %>

      <%# イベント詳細ページ 参加可否 Start %>
      <div class="channel-event-attendance">
        <% channel_user = ChannelUser.find_by(user_id: current_user.id, channel_id: @channel.id) %>
        <% is_joined = ChannelEventUser.where(channel_user_id: channel_user.id, event_id: @event.id).exists? %>
        
        <%= form_with url: channel_event_channel_event_users_path(@channel, @event), method: :post do |form| %>
          <%= form.submit "参加", class: is_joined ? "channel-event-attendance-joined" : "channel-event-attendance-not-joined", disabled: is_joined %>
        <% end %>

        <%= form_with url: channel_event_channel_event_user_path(@channel, @event), method: :delete do |form| %>
          <%= form.submit "不参加", class: is_joined ? "channel-event-attendance-not-joined" : "channel-event-attendance-joined", disabled: !is_joined %>
        <% end %>
      </div>
      <%# イベント詳細ページ 参加可否 End %>

    </div>
  </div>
  <%# イベント詳細ページ End %>
</div>