config/routes.rb
Rails.application.routes.draw do
  root to: 'channels#index'
  devise_for :users
  resources :channels do
    resources :tweets, only: [:index, :show, :create]
    resources :chats do
      resource :messages, only: [:create]
    end
    resources :events do
      resources :channel_event_users, only: [:create, :destroy]
    end
    resources :albums
    resources :topics, only: [:new ,:create,  :edit ,:update ,:destroy] 
  end
  resource :sessions, only: [:index, :new, :create, :destroy]
  resources :users, only: [:show, :edit ,:update, :destroy]
end

app/models/album.rb
class Album < ApplicationRecord
  # Association
  has_many_attached :album_images

  belongs_to :channel

  # Validation
  validates :title, presence: true
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_channel, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  def index
    @albums = if params[:search].blank?
                @channel.albums.order(created_at: :desc)
              else
                @channel.albums.where('title LIKE ?', "%#{params[:search]}%").order(created_at: :desc)
              end
  end

  def new
    @album = Album.new
  end

  def create
    @album = Album.new(album_params)

    if @album.save
      redirect_to channel_albums_path(@channel)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
  end

  def update
    if @album.update(album_params)
      redirect_to channel_albums_path(@channel)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @album.destroy
    redirect_to channel_albums_path(@channel)
  end

  private

  def set_channel
    @channel = Channel.find(session[:channel_id])
  end

  def set_album
    @album = @channel.albums.find(params[:id])
  end

  def album_params
    params.require(:album).permit(:title, { album_images: [] }).merge(channel_id: @channel.id)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/edit.html.erb
<%# チャンネル ログアウト モーダル Start %>
<%= render "shared/channel_left_modal" %>
<%# チャンネル ログアウト モーダル End %>

<%# チャンネル 共通 Start %>
<div class = "channel">

  <%# チャンネル ナビゲーション Start %>
  <%= render "shared/channel_left" %>
  <%# チャンネル ナビゲーション End %>

  <%# アルバム 編集 Start %>
  <div class = "channel-right">

    <%# アルバム 編集フォーム Start %>
    <div class = "form-left">
      <%= form_with(model:[@channel ,@album], local: true) do |f| %>

        <%# アルバム 編集フォーム ヘッダー Start %>
        <div class ="form-back">
          <%= link_to '< 戻る', :back, class:"form-back-text" %>
        </div>
        <div class ="form-title-left">
          アルバム　編集
        </div>
        <%# アルバム 編集フォーム ヘッダー End %>

        <%# アルバム 編集フォーム エラー表示 Start %>
        <div class = "form-error-left">
          <%= render 'shared/error_messages', resource: @album %>
        </div>
        <%# アルバム 編集フォーム エラー表示 End %>

        <%# アルバム 編集フォーム 入力部分 Start %>
        <div class = "form-vertical">
          <div class = "form-vertical-field">
            <%= f.label :title, "アルバム名",class:"form-field-label" %>
            <%= f.text_field :title, placeholder:"アルバム名を入力してください", autocomplete: "title", class:"form-field-string" %>
          </div>
          <div class="form-vertical-field">
            <%= f.label :alubum_image, "画像",class:"form-field-label" %>
            <div class="form-field-albumimage">
              <%= f.file_field :album_image, name: 'album[album_images][]', multiple: true, data: {index: 0} ,class:"form-field-albumimage-image" %>
            <span class="form-field-albumimage-custom">+</span>
                        </div>
            <div class="album-preview" id = "album-preview">
            </div>
          </div>
        </div>
        <%# アルバム 編集フォーム 入力部分 End %>

        <%# アルバム 編集フォーム アクション Start %>
        <div class="form-action">
          <%= f.submit "更新する",class:"form-action-submit"%>
          <div class="form-action-delete">
          削除する
          </div>

          <%# アルバム 編集フォーム アルバム削除 モーダル Start %>
          <div class ="modal" id = "modal-album-delete">
            <div class= "modal-box">
              <div class ="modal-box-title">
                本当に削除しますか？
              </div>
              <div class ="modal-actions">
                <%= link_to 'Yes', channel_album_path(@channel.id,@album), data: { turbo_method: :delete }, class:"modal-actions-y" %>
                <div class ="modal-actions-n">
                  No
                </div>
              </div>
            </div>
          </div>
          <%# アルバム 編集フォーム アルバム削除 モーダル End %>

        </div>
        <%# アルバム 新規作成フォーム アクション End %>

      <% end %>
    </div>
    <%# アルバム 編集フォーム End %>

  </div>
  <%# アルバム 編集 End %>

</div>
<%# チャンネル 共通 End %>
 

app/views/albums/index.html.erb
<%# チャンネル ログアウト モーダル Start %>
<%= render "shared/channel_left_modal" %>
<%# チャンネル ログアウト モーダル End %>

<%# チャンネル 共通 Start %>
<div class = "channel">

  <%# チャンネル ナビゲーション Start %>
  <%= render "shared/channel_left" %>
  <%# チャンネル ナビゲーション End %>

  <%# アルバム Start %>
  <div class = "channel-right">
    <div class = "channel-album">

      <%# アルバム 検索ボックス Start %>
      <%= form_tag channel_albums_path(@channel), method: :get, class: "chanel-album-search" do %>
        <%= text_field_tag :search, params[:search], placeholder: "キーワードを入力してください", class:"chanel-album-search-input" %>
          <div class = "chanel-album-search-button" >
          <%= image_submit_tag 'album/index/search.svg', class: "chanel-album-search-button-image" %>
        </div>
      <% end %>
      <%# アルバム 検索ボックス End %>

      <%# アルバム 一覧 Start %>
      <div class ="chanel-album-lists">
        <% @albums.each do |album| %>
          <%= link_to channel_album_path(@channel, album) do %>
            <div class ="chanel-album-list">
<%= album.album_images.attached? ? image_tag(url_for(album.album_images.first), class: "chanel-album-list-image") : image_tag('common/noimage.png', class: "chanel-album-list-image") %>
              <div class ="chanel-album-list-content">
                <div class ="chanel-album-list-content-title">
                  <%= album.title %>
                </div>
                <div class ="chanel-album-list-content-date">
                  <%= album.created_at.strftime('%Y年%m月%d日') + '(' + %w(日 月 火 水 木 金 土)[album.created_at.wday] + ')' %>
                </div>
                <div class ="chanel-album-list-content-sum">
                  <%= album.album_images.count %>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
      <%# アルバム 一覧 End %>
      
    </div>
  </div>
  <%# アルバム End %>

</div>
<%# チャンネル 共通 End %>

<%# アルバム 新規作成 Start %>
<%= link_to "+", new_channel_album_path(@channel) ,class:"channel-album-action" %>
<%# アルバム 新規作成 End %>

app/views/albums/new.html.erb
<%# チャンネル ログアウト モーダル Start %>
<%= render "shared/channel_left_modal" %>
<%# チャンネル ログアウト モーダル End %>

<%# チャンネル 共通 Start %>
<div class = "channel">

  <%# チャンネル ナビゲーション Start %>
  <%= render "shared/channel_left" %>
  <%# チャンネル ナビゲーション End %>

  <%# アルバム 新規作成 Start %>
  <div class = "channel-right">

    <%# アルバム 新規作成フォーム Start %>
    <div class = "form-left">
      <%= form_with(model:[@channel ,@album], local: true) do |f| %>

        <%# アルバム 新規作成フォーム ヘッダー Start %>
        <div class ="form-back">
          <%= link_to '< 戻る', :back, class:"form-back-text" %>
        </div>
        <div class ="form-title-left">
          アルバム　新規作成
        </div>
        <%# アルバム 新規作成フォーム ヘッダー End %>

        <%# アルバム 新規作成フォーム エラー表示 Start %>
        <div class = "form-error-left">
          <%= render 'shared/error_messages', resource: @album %>
        </div>
        <%# アルバム 新規作成フォーム エラー表示 End %>

        <%# アルバム 新規作成フォーム 入力部分 Start %>
        <div class = "form-vertical">
          <div class = "form-vertical-field">
            <%= f.label :title, "アルバム名",class:"form-field-label" %>
            <%= f.text_field :title, placeholder:"アルバム名を入力してください", autocomplete: "title", class:"form-field-string" %>
          </div>
          <div class="form-vertical-field">
            <%= f.label :alubum_image, "画像",class:"form-field-label" %>
            <div class="form-field-albumimage">
              <%= f.file_field :album_image, name: 'album[album_images][]', multiple: true, data: {index: 0} ,class:"form-field-albumimage-image" %>
            <span class="form-field-albumimage-custom">+</span>
                        </div>
            <div class="album-preview" id = "album-preview">
            </div>
          </div>
        </div>
        <%# アルバム 新規作成フォーム 入力部分 End %>

        <%# アルバム 新規作成フォーム アクション Start %>
        <div class="form-action">
          <%= f.submit "作成する",class:"form-action-submit"%>
        </div>
        <%# アルバム 新規作成フォーム アクション End %>

      <% end %>
    </div>
    <%# アルバム 新規作成フォーム End %>

  </div>
  <%# アルバム 新規作成 End %>

</div>
<%# チャンネル 共通 End %>

app/views/albums/show.html.erb
<%# チャンネル ログアウト モーダル Start %>
<%= render "shared/channel_left_modal" %>
<%# チャンネル ログアウト モーダル End %>

<%# チャンネル 共通 Start %>
<div class = "channel">

  <%# チャンネル ナビゲーション Start %>
  <%= render "shared/channel_left" %>
  <%# チャンネル ナビゲーション End %>

  <%# アルバム Start %>
  <div class = "channel-right">
    <div class = "channel-album">
      
      <%# アルバム ヘッダー Start %>
      <div class = "channel-album-back">
        <%= link_to '< 戻る', :back %>
      </div>
      <div class ="channel-album-title">
        <div class ="channel-album-title-name">
            <%= @album.title %>
        </div>
        <%= link_to "編集", edit_channel_album_path(@channel.id, @album) ,class:"channel-album-title-edit"  %>
      </div>
      <div class ="channel-event-date">
        <%= @album.created_at.strftime('%Y年%m月%d日') + '(' + %w(日 月 火 水 木 金 土)[@album.created_at.wday] + ')' %>
      </div>
      <%# アルバム ヘッダー End %>

      <%# アルバム 一覧 Start %>
      <div class="chanel-album-images">
        <% @album.album_images.each do |image| %>
          <%= image_tag image.blob, class: "chanel-album-image" if image.persisted? %>
        <% end %>
      </div>
      <%# アルバム 一覧 End %>
      
    </div>
  </div>
  <%# アルバム Start %>

</div>
<%# チャンネル 共通 Start %>